numeroA = 160
numeroB = 4
numeroC = 2
sumar = numeroA + numeroB + numeroC
print("el resultado de la suma es" , sumar)
print (f"la suma dio ¨{sumar} exitosamente")
restar = numeroA - numeroB -numeroC
print(f"la resta dio {restar} exitosamente")
multiplicar = numeroA * numeroB * numeroC
print (f"la multiplicacion dio {multiplicar}exitosamente")
dividir = numeroA / numeroB / numeroC
print (f"la dividicion dio {dividir} exitosamente")
exponente = numeroA**numeroB**numeroC
print (f"la operacion exponencial dio {exponente}exitosamente")